### ISSUE TITLE
[Help] How to validate the all reports are stoting in postgreSQL report-server DB

### ISSUE THREAD

**Issue by vfnp** [kyverno/reports-server#173]
Hi Team,

I have installed report-server on kubernetes cluster and edited the apiservice objects to point report-server svc, it is working fine.

Now I am looking for information that how do we validate Kyverno reports are stored on the report-server DB which is deployed as part of chart.

Also please help me to know how to generate the kyverno reports, because in my current cluster count is showing 0.

np@shell:reports-server ()$  kubectl get --raw=/metrics | grep apiserver_storage_objects | grep kyverno
apiserver_storage_objects{resource="admissionreports.kyverno.io"} 0
apiserver_storage_objects{resource="backgroundscanreports.kyverno.io"} 0
apiserver_storage_objects{resource="cleanuppolicies.kyverno.io"} 0
apiserver_storage_objects{resource="clusteradmissionreports.kyverno.io"} 0
apiserver_storage_objects{resource="clusterbackgroundscanreports.kyverno.io"} 0
apiserver_storage_objects{resource="clustercleanuppolicies.kyverno.io"} 0
apiserver_storage_objects{resource="clusterephemeralreports.reports.kyverno.io"} 0
apiserver_storage_objects{resource="clusterpolicies.kyverno.io"} 0
apiserver_storage_objects{resource="ephemeralreports.reports.kyverno.io"} 0
apiserver_storage_objects{resource="globalcontextentries.kyverno.io"} 0
apiserver_storage_objects{resource="policies.kyverno.io"} 0
apiserver_storage_objects{resource="policyexceptions.kyverno.io"} 0
apiserver_storage_objects{resource="updaterequests.kyverno.io"} 0

Thanks in advance !

**Comment by vishal-chdhry** [comment]
Hi, sorry for the late reply, you can query the database directly, the reports will be stored in reportsdb database and the tables should be policyreports, clusterpolicyreports, ephemeralreports and clusterephemeralreports
