### ISSUE TITLE
DB Conflict: create clusterpolicyreport: pq: duplicate key value violates unique constraint "clusterpolicyreports_pkey"

### ISSUE THREAD

**Issue by mcoreix** [kyverno/reports-server#174]
I am using kyverno-reports-server with external Postgres Cluster using CloudnativePG Operator v16.3
Once restarting the kyverno-reports-server pod, i get this error:

`
I0807 07:09:42.387073 1 cpolr.go:88] creating entry for key:00269f9b-6f65-424b-8165-e58f2e69dcb4
E0807 07:09:42.389862 1 cpolr.go:98] "failed to crate cpolr" err="pq: duplicate key value violates unique constraint \"clusterpolicyreports_pkey\""
E0807 07:09:42.389896 1 config.go:59] create clusterpolicyreport: pq: duplicate key value violates unique constraint "clusterpolicyreports_pkey"
Error: create clusterpolicyreport: pq: duplicate key value violates unique constraint "clusterpolicyreports_pkey"
.
.
.
panic: create clusterpolicyreport: pq: duplicate key value violates unique constraint "clusterpolicyreports_pkey"
goroutine 1 [running]:
main.main()
github.com/kyverno/reports-server/main.go:20 +0x8b
`

it is trying to recreate the reports....but once the name is there, it should update the values instead of insert

**Comment by mcoreix** [comment]
any updates here?

**Comment by vishal-chdhry** [comment]
@mcoreix sorry for the delayed response, I think this happens because of reports server trying to migrate reports, working on the fix

**Comment by paolocarta** [comment]
Having the same issue after the Server is running for some time. As soon as I restart the Reports Server Pod it has this issue.

Logs:
```
I0912 08:13:52.647476       1 store.go:16] setting up storage, debug=false
I0912 08:13:52.647524       1 new.go:20] starting postgres db, config: 
I0912 08:13:52.647547       1 new.go:28] pinging postgres db, attempt: 1
I0912 08:13:52.660907       1 new.go:43] successfully connected to db
I0912 08:13:52.660929       1 new.go:45] starting reports store
I0912 08:13:52.664802       1 new.go:70] successfully setup storage
I0912 08:13:52.664837       1 config.go:57] performing migration...
I0912 08:13:52.679494       1 cpolr.go:88] creating entry for key:92a4f537-20c7-458b-bdcd-734939b5c3f0
E0912 08:13:52.681843       1 cpolr.go:98] "failed to crate cpolr" err="pq: duplicate key value violates unique constraint \"clusterpolicyreports_pkey\""
E0912 08:13:52.681901       1 config.go:59] create clusterpolicyreport: pq: duplicate key value violates unique constraint "clusterpolicyreports_pkey"
Error: create clusterpolicyreport: pq: duplicate key value violates unique constraint "clusterpolicyreports_pkey"
```

**Comment by my-life-for-auir** [comment]
Hello, I'm using what I believe is the latest version of reports-server and I'm still running into this issue.

Image:

```
ghcr.io/kyverno/reports-server:v0.1.1
```

```
I1212 00:22:17.435178       1 store.go:16] setting up storage, debug=false
I1212 00:22:17.435218       1 new.go:20] starting postgres db, config: host=10.37.68.26 port=5432 user=password= dbname=postgres sslmode=disable sslrootcert= sslkey= sslcert=
I1212 00:22:17.435239       1 new.go:28] pinging postgres db, attempt: 1
I1212 00:22:17.446391       1 new.go:43] successfully connected to db
I1212 00:22:17.446405       1 new.go:45] starting reports store
I1212 00:22:17.460320       1 new.go:70] successfully setup storage
I1212 00:22:17.460341       1 config.go:57] performing migration...
I1212 00:22:17.486496       1 cpolr.go:88] creating entry for key:03cc6084-69e2-4085-9265-e7df793cb873
E1212 00:22:17.490404       1 cpolr.go:98] "failed to crate cpolr" err="pq: duplicate key value violates unique constraint \"clusterpolicyreports_pkey\""
E1212 00:22:17.490430       1 config.go:59] create clusterpolicyreport: pq: duplicate key value violates unique constraint "clusterpolicyreports_pkey"
Error: create clusterpolicyreport: pq: duplicate key value violates unique constraint "clusterpolicyreports_pkey"
```
