### ISSUE TITLE
Docs: double dash seems to be not correct

### ISSUE THREAD

**Issue by larsvomsee** [kyverno/reports-server#218]
Dear Guys,

looks like there is a typo in the install.md. With my helm version I get a error unknown argument.

helm version:
`version.BuildInfo{Version:"v3.16.1", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"clean", GoVersion:"go1.22.7"}`

cmd:
`helm search repo reports-server --l`

error:
`Error: unknown flag: --l`

Code line:
https://github.com/kyverno/reports-server/blob/c0d75ef0a5e3eb8d1a569c398a067e7aaaeb3767/docs/INSTALL.md?plain=1#L31

man page:
` -l, --versions             show the long listing, with each version of each chart on its own line, for repositories you have added`

solution:
```
helm search repo reports-server -l
or
helm search repo reports-server --versions
```

**Comment by vishal-chdhry** [comment]
Fixed it in latest commit
